schema_version: 1

context:
  version: "1.4.0"

package:
  name: libpisp
  version: ${{ version }}

source:
  url: https://github.com/raspberrypi/libpisp/archive/v${{ version }}.tar.gz
  sha256: 314c6caea5c753f4b353df131d8b8626b70bfa38b76d8658698918cc0f7c1614

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - meson
    - ninja
    - python
    - pkg-config
  host:
    - nlohmann_json
  run_exports:
    - ${{ pin_subpackage('libpisp', upper_bound='x.x.x') }}

tests:
  - package_contents:
      lib:
        - pisp
about:
  summary: Library for interfacing with the Raspberry Pi PISP
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/raspberrypi/libpisp

extra:
  recipe-maintainers:
    - carlodri
